### ISSUE TITLE
Support for AM/PM

### ISSUE THREAD

**Issue by SamPlusPlus** [commandiron/WheelPickerCompose#7]
I would like to support AM and PM as well as 24-hour format. Is this something you are considering?

**Comment by commandiron** [comment]
hey Sam thanks for your feedback. AM PM support has crossed my mind too, but this feature completely changes the layout because the user must specify whether the selected time is AM or PM so that snappedDate is given correctly. AM/PM button should be added so that this can be done. I will work on it as soon as possible. Thanks again.

**Comment by commandiron** [comment]
hi, i add AM/PM support, [this](https://github.com/commandiron/WheelPickerCompose/releases/tag/1.1.4) release has this option as timeFormat param. in time picker, however with date picker AM/PM time picker not working correctly, i will solve this problem later and release another version later. Thanks.

**Comment by SamPlusPlus** [comment]
@commandiron I can try and take a look at this and give some feedback if
that would be helpful. I look forward to the future release. Ty for taking
a look at this!
